apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-controller
spec:
  replicas: 3
  selector:
    name: rc
  template:
    metadata:
      labels:
        name: rc
    spec:
      containers:
      - name: rcc-container
        image: nginx
