apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    app: web
spec:
  containers:
    - name: one
      image: nginx
      ports:
        - containerPort: 80
      command: ['sh', '-c', 'echo Hello this is container 1! && sleep 3600']

    - name: two
      image: busybox
      ports:
        - containerPort: 8080
      command: ['sh', '-c', 'echo Hello this is container 2! && sleep 3600']
