apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deploy
spec:
  replicas: 3
  strategy: # 미 설정 시 type: rollingUpdate 및 아래의 설정이 default
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: ho
  template:
    metadata:
      labels: 
        app: ho
    spec:
      containers:
      - image: nginx:1.16
        name: deploy-container
