apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deploy
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ho
  template:
    metadata:
      labels: 
        app: ho
    spec:
      containers:
      - image: nginx:1.16
        name: deploy-container
