apiVersion: v1
kind: Pod
metadata:
  name: use-pv-pod
spec:
  containers:
  - name: pv-container
    image: nginx:1.14
    volumeMounts:
    - name: pv-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: pvc-web
  
